# we actually need both environments PHP and rvm
# however it is only possible to define the environment for one
# language
language: php
rvm: 1.8.7
php:
  - 5.4

notifications:
  email:
    - dev@frankstelzer.de
env:
  - PUPPET_VERSION=2.7.11

before_script:
  - composer install

# PHPUnit tests only, rake spec could not be done within the same travis worker
# (ruby is installed on a PHP worker but .gemfile will be ignored)
script: phpunit --coverage-text --configuration phpunit_ci.xml

# whitelist
branches:
  only:
    - spec