parameters:

services:
    puphpet.extension.mysql.manifest_renderer:
        parent: puphpet.template_renderer
        calls:
            - [setTemplateFile, ['PuphpetExtensionMysqlBundle:manifest:Mysql.pp.twig']]

    puphpet.extension.mysql.configure:
        class: Puphpet\Extension\MysqlBundle\Configure
        arguments:
            - "@service_container"
            - "@puphpet.extension.mysql.manifest_renderer"

    puphpet.extension.mysql.front_controller:
        class: Puphpet\Extension\MysqlBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]
